import { EquipmentPiece, PlayerSkills } from '@/types/Player';
import requirementsJson from '../../cdn/json/requirements.json';

/**
 * Equipment level requirements by item name, generated by scripts/sync-reqs.mjs
 * from wiki lead sections (the wiki has no structured requirements data).
 * Items absent from the map have no known level requirements.
 */
export interface ItemRequirements {
  atk?: number;
  str?: number;
  def?: number;
  ranged?: number;
  magic?: number;
  prayer?: number;
  hp?: number;
  slayer?: number;
}

const REQUIREMENTS = requirementsJson as Record<string, ItemRequirements>;

export const requirementsOf = (name: string): ItemRequirements | undefined => REQUIREMENTS[name];

/** whether base (unboosted) levels are high enough to equip the item */
export function meetsRequirements(item: EquipmentPiece, skills: PlayerSkills, slayerLevel = 99): boolean {
  const reqs = REQUIREMENTS[item.name];
  if (!reqs) return true;
  return (reqs.atk ?? 0) <= skills.atk
    && (reqs.str ?? 0) <= skills.str
    && (reqs.def ?? 0) <= skills.def
    && (reqs.ranged ?? 0) <= skills.ranged
    && (reqs.magic ?? 0) <= skills.magic
    && (reqs.prayer ?? 0) <= skills.prayer
    && (reqs.hp ?? 0) <= skills.hp
    && (reqs.slayer ?? 0) <= slayerLevel;
}
